// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxvmjhyuowqwtlyuwesy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94dm1qaHl1b3dxd3RseXV3ZXN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MjEyMTgsImV4cCI6MjA2ODk5NzIxOH0.xMDY53be5dT5tZNGN87Oay508CTBqr7Mau6nDq3QxKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});